openapi: 3.0.0
info:
  title: Delete a user data
  description: Soft Delete user data in database
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development Server 
paths:
  "/users/{id}":
    delete:
      tags:
        - User
      summary: Delete user data.
      description: Delete endpoint for soft delete 
      parameters:
        - name: id 
          in: path 
          required: true 
          schema:
            type: string 
      responses:
        "200":
          description: Success Response 
          content:
            "application/json":
              schema:
                type: object 
                properties:
                  statusCode:
                    type: number 
                    example: 200
                  success:
                    type: boolean
                    example: true 
                  message: 
                    type: string 
                    example: User data is deleted successfully 
                  data: 
                    type: object 
                    example: {}