openapi: 3.0.0
info: 
  title: User Management API
  description: This API allows you to retrieve all user data. 
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development Server 
paths:
  "/users":
    get:
      summary: Get all users 
      description: This endpoint retrieves a list of all users in the system.
      responses:
        "200": 
          description: Successfully fetched all users' data 
          content:
            "application/json":
              schema:
                type: object
                properties:
                  statusCode: 
                    type: number
                    example: 200
                  success: 
                    type: boolean
                    example: true
                  message: 
                    type: string
                    example: Users are retrieved successfully
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: 60c72b2f9b1d4a3b3c1b2c8e
                          description: Unique identifier for the user (MongoDB ObjectId)
                        fullName: 
                          type: string
                          example: Moshfiqur Rahman
                          description: The full name of the user 
                        email:
                          type: string
                          example: moshfiqur@gmail.com
                          description: The email address of the user
                        role: 
                          type: string
                          default: user 
                          description: The role of the user within the system
                        isDeleted:
                          type: boolean
                          default: false
                          description: Indicates whether the user is marked as deleted
                        createdAt:
                          type: string
                          format: date-time
                          example: "2024-12-23T15:30:00Z"
                          description: The date and time when the user was created
                        updatedAt:
                          type: string
                          format: date-time
                          example: "2024-12-23T15:30:00Z"
                          description: The date and time when the user's information was last updated